
SELECT * FROM Copy_LND_CONV_R2_4_ATTORNEY WHERE NM_ATTY LIKE '%ESQ%'

SELECT * FROM Copy_LND_CONV_R2_4_ATTORNEY WHERE NM_ATTY LIKE '%*%'

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', ESQ***','');

AARON T JAINCHILL,  ESQ ***

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,',  ESQ ***','');

LANCE E COUGHLIN ESQ ***

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,'  ESQ ***','');


update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,'ESQ***','');

AARON T JAINCHILL***, ESQ
update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,'***, ESQ','');

ZINGARO & CRETELLA, LLC ***

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', LLC ***','');

CHRISTOPHER B CARVETH,ESQ***

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,',ESQ***','');

JOHN C TURNER JR ***

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,' ***','');

MICHAEL L RILEY, ESQ.***

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', ESQ.***','');

MATTHEW COLLINS, ESQ

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,', ESQ','');

VINCENT J MASE SR,  ESQ.**

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',  ESQ.**','');

SHAWN M O NEILL ESQ **

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,' ESQ **','');

AARON J ROMANO,  ESQ

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',  ESQ','');

THOMAS E CROSBY ESQ

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,' ESQ','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',  ESQ.','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'.**','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'. **','');

SELECT * FROM Copy_LND_CONV_R2_4_ATTORNEY WHERE NM_ATTY LIKE '%*%'

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,' **','');        -----------------------------------------

ZINGARO & CRETELLA, LLC***
update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', LLC***','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'**','');


update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,' *','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',ESQ*','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',ESQ.*','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'.*','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,' *','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'*','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'.ESQ.','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,' ,ESQ.','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',ESQ.','');

update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,',ESQ','');


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,' ,LLC','');
THOMAS J ALLINGHAM LLC
JENNIFER J TUNNARD ,LLC
SELECT * FROM PROD_ABF WHERE NM_ATTY LIKE '%LLC%' 

SELECT * FROM PROD_ABF WHERE NM_ATTY LIKE '%PC%' 


update PROD_ABF set NM_ATTY=REPLACE(NM_ATTY,'.','');




------------------------------------------------------------for others





SELECT * FROM Copy_LND_CONV_R2_4_ATTORNEY WHERE NM_ATTY LIKE '%ESQ%'

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', ESQ','');

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,' ESQ','');


SELECT * FROM Copy_LND_CONV_R2_4_ATTORNEY WHERE NM_ATTY LIKE '%,'


SELECT * FROM Copy_LND_CONV_R2_4_ATTORNEY WHERE NM_ATTY LIKE '%LLC%'

YAMIN & GRANT, LLC

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', LLC','');

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,' LLC','');

BARTINIK LAW FIRM, PC

update Copy_LND_CONV_R2_4_ATTORNEY set NM_ATTY=REPLACE(NM_ATTY,', PC','');
